### ISSUE TITLE
add support for Python 3.10

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/mzml2isa#47]
requires upgrading  Pronto ontology parsing component from v=0.12 to v2.5.0

currently, code breaks here:
https://github.com/ISA-tools/mzml2isa/blob/acf4220d000418776006b3c89c1014c4f658c30d/mzml2isa/mzml.py#L105

@althonos @Tomnl any hint regarding the pronto changes?

**Comment by althonos** [comment]
I'll have a look, I think I need to cache some more things wrt `pronto` because of performance issues with the newer versions :+1:

**Comment by proccaserra** [comment]
@althonos Thx for the super swift feedback! We are looking at making a release of the ISA-API and adding support for 3.10.
@terazus has a fix for pronto 0.12.2 (see below) but since pronto is at 2.5.0 (scream) ! makes little sense to send a PR :).

Line 28: Class Ontology( collections.abc.mappings) instead of Class Ontology(collections.mappings) in Ontology.py in the library.

So we have a fix but can't release.

Please let us how busy you are the moment! 
ATB

**Comment by terazus** [comment]
Hello,
The problem seems to be originating from the version of pronto that mzml2isa uses.
It's old and a bit outdated but can be easily modified to fit our needs.
The version of pronto is  0.12.2. In Ontology.py the Ontology class inheritance needs to be changed from
`collections.mapping` to `collections.abc.mapping` or `typing.mapping.`

Hope this can help to make a quick fix.

**Comment by althonos** [comment]
Do you want me to make a new release?

**Comment by proccaserra** [comment]
@althonos only if you have time ! either way, many thanks for the quick fix to the library.

**Comment by Tomnl** [comment]
Thanks @althonos for sorting this!
